#ifndef FIGCONE_SHORTMACROS_H
#define FIGCONE_SHORTMACROS_H

#include "figcone/detail/configmacros.h"

#define PARAM FIGCONE_PARAM
#define NODE FIGCONE_NODE
#define COPY_NODELIST FIGCONE_COPY_NODELIST
#define NODELIST FIGCONE_NODELIST
#define PARAMLIST FIGCONE_PARAMLIST
#define DICT FIGCONE_DICT

#endif //FIGCONE_SHORTMACROS_H